server:
  port: 8080

spring:
  application:
    name: tunesphere

  datasource:
    url: jdbc:postgresql://postgres:5432/tunesphere
    username: postgres
    password: 54368
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: tunesphere-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.tunesphere.event"
        spring.json.type.mapping: "SongPlayedEvent:com.tunesphere.event.SongPlayedEvent"

# ==================== JWT ====================
jwt:
  secret: "superSecretKeyForTuneSphere2026ChangeMeInProduction1234567890abcdef"
  expiration: 86400000
  refresh-expiration: 604800000   # 7 дней

# ==================== Uploads ====================
app:
  upload:
    base-dir: /app/uploads
    songs-dir: ${app.upload.base-dir}/songs
    covers-dir: ${app.upload.base-dir}/covers
    avatars-dir: ${app.upload.base-dir}/avatars