CREATE TABLE users(
id BIGSERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) NOT NULL CHECK(role IN ('USER')),
avatar_url VARCHAR(200),
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE albums(
id BIGSERIAL PRIMARY KEY,
title VARCHAR(100),
description VARCHAR(2000) NULL,
release_year DATE NOT NULL DEFAULT NOW(),
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE songs(
id BIGSERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
lyrics VARCHAR(2000),
album_id BIGINT REFERENCES albums(id) ON DELETE CASCADE,
duration INTEGER NOT NULL,
audio_url VARCHAR(100) NOT NULL,
play_count BIGINT DEFAULT 0,
genre VARCHAR(50),
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE playlists(
id BIGSERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description VARCHAR(500) CHECK(CHARACTER_LENGTH(description) > 3),
isPublic boolean DEFAULT FALSE,
user_id BIGINT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE artists(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE,
bio VARCHAR(2000) NOT NULL,
avatar_url VARCHAR(200),
email VARCHAR(100) NOT NULL UNIQUE,
role VARCHAR(20) NOT NULL,
followers_count BIGINT DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


CREATE TABLE albums_artists(
albums_id BIGINT REFERENCES albums_id ON DELETE CASCADE,
artists_id BIGINT REFERENCES artists_id ON DELETE CASCADE,
PRIMARY KEY (albums_id,artists_id)
);
CREATE TABLE albums_songs(
albums_id BIGINT REFERENCES albums_id ON DELETE CASCADE,
artists_id BIGINT REFERENCES artists_id ON DELETE CASCADE,
PRIMARY KEY(albums_id,songs_id)
);
CREATE TABLE songs_playlist(
playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
song_id BIGINT REFERENCES songs(id) ON DELETE CASCADE,
PRIMARY KEY (playlist_id,song_id)
);
CREATE TABLE songs_artists(
artists_id BIGINT REFERENCES artists_id ON DELETE CASCADE,
song_id BIGINT REFERENCES songs(id) ON DELETE CASCADE,
PRIMARY KEY (artists_id,song_id)
);
