CREATE TABLE users(
id BIGSERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) NOT NULL,
avatar_url VARCHAR(100),
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL
);
CREATE TABLE songs(
id BIGSERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
duration INTEGER NOT NULL,
audio_url VARCHAR(100) NOT NULL,
play_count BIGINT DEFAULT 0,
genre VARCHAR,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL
);

